# Generated by Django 5.2.9 on 2025-12-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('PRIVADO', 'Privado'), ('GOBIERNO', 'Gobierno')], max_length=20)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['name'],
            },
        ),
    ]
