# Generated by Django 5.2.9 on 2025-12-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='direction',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nacionality',
            new_name='nationality',
        ),
    ]
